function randomDateThisMonth() {
    const now = new Date();
    const start = new Date(now.getFullYear(), now.getMonth(), 1);
    const end = now;
    return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime())).toISOString();
}

function randomProductIds() {
    const possible = ["prod_001", "prod_002", "prod_003", "prod_004", "prod_005", "prod_006", "prod_007", "prod_008", "prod_009", "prod_010"];
    const n = Math.floor(Math.random() * 4); // 0, 1, 2, 3
    return Array.from({ length: n }, () => possible[Math.floor(Math.random() * possible.length)]);
}

export const videos = [
    {
        id: "video-1",
        thumbnailUrl: "https://picsum.photos/id/1011/160/200",
        filename: "white-dress-1.mp4",
        duration: "0:14",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5), // 5–50 МБ
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-2",
        thumbnailUrl: "https://picsum.photos/id/1012/160/200",
        filename: "summer-look-2.mp4",
        duration: "0:21",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-3",
        thumbnailUrl: "https://picsum.photos/id/1015/160/200",
        filename: "black-glam-3.mp4",
        duration: "0:37",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-4",
        thumbnailUrl: "https://picsum.photos/id/1016/160/200",
        filename: "evening-style-4.mp4",
        duration: "0:09",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-5",
        thumbnailUrl: "https://picsum.photos/id/1020/160/200",
        filename: "green-outfit-5.mp4",
        duration: "0:55",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-6",
        thumbnailUrl: "https://picsum.photos/id/1024/160/200",
        filename: "classic-chic-6.mp4",
        duration: "0:32",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-7",
        thumbnailUrl: "https://picsum.photos/id/1025/160/200",
        filename: "leopard-walk-7.mp4",
        duration: "0:26",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-8",
        thumbnailUrl: "https://picsum.photos/id/1027/160/200",
        filename: "party-glitter-8.mp4",
        duration: "0:46",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-9",
        thumbnailUrl: "https://picsum.photos/id/1028/160/200",
        filename: "midi-skirt-9.mp4",
        duration: "0:35",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-10",
        thumbnailUrl: "https://picsum.photos/id/1033/160/200",
        filename: "fashion-show-10.mp4",
        duration: "0:28",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-11",
        thumbnailUrl: "https://picsum.photos/id/1035/160/200",
        filename: "cocktail-11.mp4",
        duration: "0:17",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-12",
        thumbnailUrl: "https://picsum.photos/id/1036/160/200",
        filename: "urban-mood-12.mp4",
        duration: "0:52",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-13",
        thumbnailUrl: "https://picsum.photos/id/1042/160/200",
        filename: "street-trend-13.mp4",
        duration: "0:45",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-14",
        thumbnailUrl: "https://picsum.photos/id/1043/160/200",
        filename: "red-glam-14.mp4",
        duration: "0:11",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-15",
        thumbnailUrl: "https://picsum.photos/id/1044/160/200",
        filename: "vintage-moment-15.mp4",
        duration: "0:30",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-16",
        thumbnailUrl: "https://picsum.photos/id/1045/160/200",
        filename: "casual-chic-16.mp4",
        duration: "0:39",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-17",
        thumbnailUrl: "https://picsum.photos/id/1049/160/200",
        filename: "office-look-17.mp4",
        duration: "0:27",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-18",
        thumbnailUrl: "https://picsum.photos/id/1050/160/200",
        filename: "date-night-18.mp4",
        duration: "0:44",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-19",
        thumbnailUrl: "https://picsum.photos/id/1051/160/200",
        filename: "pastel-vibe-19.mp4",
        duration: "0:42",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-20",
        thumbnailUrl: "https://picsum.photos/id/1052/160/200",
        filename: "spring-style-20.mp4",
        duration: "0:50",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-21",
        thumbnailUrl: "https://picsum.photos/id/1053/160/200",
        filename: "holiday-dress-21.mp4",
        duration: "0:18",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-22",
        thumbnailUrl: "https://picsum.photos/id/1054/160/200",
        filename: "boho-glam-22.mp4",
        duration: "0:54",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-23",
        thumbnailUrl: "https://picsum.photos/id/1055/160/200",
        filename: "lace-touch-23.mp4",
        duration: "0:33",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-24",
        thumbnailUrl: "https://picsum.photos/id/1056/160/200",
        filename: "pink-flair-24.mp4",
        duration: "0:31",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-25",
        thumbnailUrl: "https://picsum.photos/id/1057/160/200",
        filename: "minimal-black-25.mp4",
        duration: "0:41",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-26",
        thumbnailUrl: "https://picsum.photos/id/1058/160/200",
        filename: "retro-vibe-26.mp4",
        duration: "0:58",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-27",
        thumbnailUrl: "https://picsum.photos/id/1059/160/200",
        filename: "autumn-leaf-27.mp4",
        duration: "0:16",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-28",
        thumbnailUrl: "https://picsum.photos/id/1060/160/200",
        filename: "long-dress-28.mp4",
        duration: "0:29",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-29",
        thumbnailUrl: "https://picsum.photos/id/1061/160/200",
        filename: "short-dress-29.mp4",
        duration: "0:49",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
    {
        id: "video-30",
        thumbnailUrl: "https://picsum.photos/id/1062/160/200",
        filename: "off-shoulder-30.mp4",
        duration: "0:12",
        format: "MP4",
        size: Math.floor(Math.random() * 45 + 5),
        createdAt: randomDateThisMonth(),
        productIds: randomProductIds(),
    },
];
