# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "60ce8b60b01060a28f4c944056f0aabc"
name = "video-app"
handle = "video-app-15"
application_url = "https://f3ce79b5d1b7.ngrok-free.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_files, read_themes, read_images"

[auth]
redirect_urls = [
  "https://f3ce79b5d1b7.ngrok-free.app/auth/callback",
  "https://f3ce79b5d1b7.ngrok-free.app/auth/shopify/callback",
  "https://f3ce79b5d1b7.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
